name: persian_datetime_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 2.3.0
author: Mohammad amir mohammdi <mem.amir.m@gamil.com>
homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: SG-Main
      fonts:
        - asset: assets/fonts/sg_kara_light.ttf
          weight: 300
        - asset: assets/fonts/sg_kara_regular.ttf
        - asset: assets/fonts/sg_kara_semi_bold.ttf
          weight: 600


